name = "heuristicopt"
uuid = "5d31eb41-a555-527e-bc3a-b0a396a41ac3"
authors = ["ariririri <fatal.t.h.f.flydream.bamboo@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
